;; In-game command:
; /craft <Recipe Name> <amount>
; /dismantle <Recipe Name> <amount>
; /loot <Recipe Name> <amount>

;; Syntax:
; [<Recipe Name>]
; type = produce/dismantle/loot
; product = <good nickname>, <min amount>, <max amount>, <weighted chance> ;multiple times allowed
; ingredient = <good nickname>, <amount> ;multiple times allowed
; cost = <amount> ;optional
; base_nickname = <base nickname> ;optional, multiple times allowed
; ship_nickname = <shiparch nickname> ;optional, multiple times allowed
; success_sound_nickname = <sound nickname> ;optional


;; ----------------------------
;; DISMANTLING - COMMODITIES
;; ----------------------------

;; - Active Artifacts -
;; 		Available on:
;;				Toledo
;;				Baxter
;;				Willard
;;				Kansai
;;				Nansei
;; 				Jena
;;				Mactan
;;				Ames

[Active Artifacts]
type = dismantle
product = commodity_scrap_metal, 1, 5, 97
product = commodity_nadnium_crystals, 1, 2, 3
ingredient = commodity_active_artifacts, 1
cost = 10000
base_nickname = St01_01_base
base_nickname = Bw01_05_base
base_nickname = Li02_04_base
base_nickname = Ku04_04_base
base_nickname = Ku03_04_base
base_nickname = Rh04_08_base
base_nickname = Iw03_02_base
base_nickname = Iw05_01_base
success_sound_nickname = Crafting_successful_light

;; ----------------------------
;; DISMANTLING - LIGHTS
;; ----------------------------


;; -LIGHT PACKAGES PATRIOT -
;; 		Available on:
;;				Everywhere

[Lights: Patriot - Red]
type = dismantle
product = material_red_lights, 1, 2, 1
ingredient = SlowSmallRed_li_fighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Patriot - Blue]
type = dismantle
product = material_blue_lights, 1, 2, 1
ingredient = SlowSmallBlue_li_fighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Patriot - Green]
type = dismantle
product = material_green_lights, 1, 2, 1
ingredient = SlowSmallGreen_li_fighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Patriot - Yellow]
type = dismantle
product = material_yellow_lights, 1, 2, 1
ingredient = SlowSmallYellow_li_fighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Patriot - Orange]
type = dismantle
product = material_orange_lights, 1, 2, 1
ingredient = SlowSmallOrange_li_fighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Patriot - Purple]
type = dismantle
product = material_purple_lights, 1, 2, 1
ingredient = SlowSmallPurple_li_fighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Patriot - Pink]
type = dismantle
product = material_pink_lights, 1, 2, 1
ingredient = SlowSmallPink_li_fighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Patriot - White]
type = dismantle
product = material_white_lights, 1, 2, 1
ingredient = SlowSmallWhite_li_fighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Patriot - Sky Blue]
type = dismantle
product = material_skyblue_lights, 1, 2, 1
ingredient = SlowSmallSkyBlue_li_fighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Patriot - Cyan]
type = dismantle
product = material_cyan_lights, 1, 2, 1
ingredient = SlowSmallCyan_li_fighter01, 1
success_sound_nickname = Crafting_successful_electrical

;; -LIGHT PACKAGES DEFENDER -
;; 		Available on:
;;				Everywhere

[Lights: Defender - Red]
type = dismantle
product = material_red_lights, 1, 2, 1
ingredient = SlowSmallRed_li_elite01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Defender - Blue]
type = dismantle
product = material_blue_lights, 1, 2, 1
ingredient = SlowSmallBlue_li_elite01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Defender - Green]
type = dismantle
product = material_green_lights, 1, 2, 1
ingredient = SlowSmallGreen_li_elite01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Defender - Yellow]
type = dismantle
product = material_yellow_lights, 1, 2, 1
ingredient = SlowSmallYellow_li_elite01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Defender - Orange]
type = dismantle
product = material_orange_lights, 1, 2, 1
ingredient = SlowSmallOrange_li_elite01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Defender - Purple]
type = dismantle
product = material_purple_lights, 1, 2, 1
ingredient = SlowSmallPurple_li_elite01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Defender - Pink]
type = dismantle
product = material_pink_lights, 1, 2, 1
ingredient = SlowSmallPink_li_elite01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Defender - White]
type = dismantle
product = material_white_lights, 1, 2, 1
ingredient = SlowSmallWhite_li_elite01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Defender - Sky Blue]
type = dismantle
product = material_skyblue_lights, 1, 2, 1
ingredient = SlowSmallSkyBlue_li_elite01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Defender - Cyan]
type = dismantle
product = material_cyan_lights, 1, 2, 1
ingredient = SlowSmallCyan_li_elite01, 1
success_sound_nickname = Crafting_successful_electrical

;; -LIGHT PACKAGES ENFORCER -
;; 		Available on:
;;				Everywhere

[Lights: Enforcer - Red]
type = dismantle
product = material_red_lights, 1, 2, 1
ingredient = SlowSmallRed_li_elite02, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Enforcer - Blue]
type = dismantle
product = material_blue_lights, 1, 2, 1
ingredient = SlowSmallBlue_li_elite02, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Enforcer - Green]
type = dismantle
product = material_green_lights, 1, 2, 1
ingredient = SlowSmallGreen_li_elite02, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Enforcer - Yellow]
type = dismantle
product = material_yellow_lights, 1, 2, 1
ingredient = SlowSmallYellow_li_elite02, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Enforcer - Orange]
type = dismantle
product = material_orange_lights, 1, 2, 1
ingredient = SlowSmallOrange_li_elite02, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Enforcer - Purple]
type = dismantle
product = material_purple_lights, 1, 2, 1
ingredient = SlowSmallPurple_li_elite02, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Enforcer - Pink]
type = dismantle
product = material_pink_lights, 1, 2, 1
ingredient = SlowSmallPink_li_elite02, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Enforcer - White]
type = dismantle
product = material_white_lights, 1, 2, 1
ingredient = SlowSmallWhite_li_elite02, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Enforcer - Sky Blue]
type = dismantle
product = material_skyblue_lights, 1, 2, 1
ingredient = SlowSmallSkyBlue_li_elite02, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Enforcer - Cyan]
type = dismantle
product = material_cyan_lights, 1, 2, 1
ingredient = SlowSmallCyan_li_elite02, 1
success_sound_nickname = Crafting_successful_electrical

;; -LIGHT PACKAGES RHINO -
;; 		Available on:
;;				Everywhere

[Lights: Rhino - Red]
type = dismantle
product = material_red_lights, 1, 2, 1
ingredient = SlowSmallRed_li_freighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Rhino - Blue]
type = dismantle
product = material_blue_lights, 1, 2, 1
ingredient = SlowSmallBlue_li_freighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Rhino - Green]
type = dismantle
product = material_green_lights, 1, 2, 1
ingredient = SlowSmallGreen_li_freighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Rhino - Yellow]
type = dismantle
product = material_yellow_lights, 1, 2, 1
ingredient = SlowSmallYellow_li_freighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Rhino - Orange]
type = dismantle
product = material_orange_lights, 1, 2, 1
ingredient = SlowSmallOrange_li_freighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Rhino - Purple]
type = dismantle
product = material_purple_lights, 1, 2, 1
ingredient = SlowSmallPurple_li_freighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Rhino - Pink]
type = dismantle
product = material_pink_lights, 1, 2, 1
ingredient = SlowSmallPink_li_freighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Rhino - White]
type = dismantle
product = material_white_lights, 1, 2, 1
ingredient = SlowSmallWhite_li_freighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Rhino - Sky Blue]
type = dismantle
product = material_skyblue_lights, 1, 2, 1
ingredient = SlowSmallSkyBlue_li_freighter01, 1
success_sound_nickname = Crafting_successful_electrical

[Lights: Rhino - Cyan]
type = dismantle
product = material_cyan_lights, 1, 2, 1
ingredient = SlowSmallCyan_li_freighter01, 1
success_sound_nickname = Crafting_successful_electrical