;; In-game command:
; /craft <Recipe Name> <amount>
; /dismantle <Recipe Name> <amount>
; /loot <Recipe Name> <amount>

;; Syntax:
; [<Recipe Name>]
; type = produce/dismantle/loot
; product = <good nickname>, <min amount>, <max amount>, <weighted chance> ;multiple times allowed
; ingredient = <good nickname>, <amount> ;multiple times allowed
; cost = <amount> ;optional
; base_nickname = <base nickname> ;optional, multiple times allowed
; ship_nickname = <shiparch nickname> ;optional, multiple times allowed
; success_sound_nickname = <sound nickname> ;optional

[General]
success_sound_nickname = Crafting_successful_refining
fail_sound_nickname = ui_select_reject
