;; In-game command:
; /craft <Recipe Name> <amount>
; /dismantle <Recipe Name> <amount>
; /loot <Recipe Name> <amount>

;; Syntax:
; [<Recipe Name>]
; type = produce/dismantle/loot
; product = <good nickname>, <min amount>, <max amount>, 1, 1, <weighted chance> ;multiple times allowed
; ingredient = <good nickname>, <amount> ;multiple times allowed, 1
; cost = <amount> ;optional
; base_nickname = <base nickname> ;optional, multiple times allowed
; ship_nickname = <shiparch nickname> ;optional, multiple times allowed
; success_sound_nickname = <sound nickname> ;optional

;; ---------------------
;; DROPABLE BOXES
;; ---------------------

[Bronze Crate]
type = loot
ingredient = surprise_box_loot_bronze01, 1
product = blueprint_cv_gun_laser_light02, 1, 1, 1
product = blueprint_cv_gun_photon_light02, 1, 1, 1
product = blueprint_gd_im_gun_tachyon_light02, 1, 1, 1
product = commodity_lots_of_credits, 1, 1, 1
success_sound_nickname = ui_gain_level

[Silver Crate]
type = loot
ingredient = surprise_box_loot_silver01, 1
product = blueprint_cv_gun_laser_medium02, 1, 1, 1
product = blueprint_cv_gun_photon_medium02, 1, 1, 1
product = blueprint_gd_im_gun_tachyon_medium02, 1, 1, 1
product = blueprint_cv_gun_particle_heavy02, 1, 1, 1
product = blueprint_cv_gun_plasma_heavy02, 1, 1, 1
success_sound_nickname = ui_gain_level

[Gold Crate]
type = loot
ingredient = surprise_box_loot_gold01, 1
product = surprise_box_blueprint_guns01, 1, 1, 25
product = blueprint_cv_power_light_opt01, 1, 1, 10
product = blueprint_cv_power_medium_opt01, 1, 1, 10
product = blueprint_cv_power_heavy_opt01, 1, 1, 10
product = blueprint_ge_cloak_fighter_std01, 1, 1, 2
product = material_gunboat_data_recorder, 1, 1, 20
product = material_cruiser_data_recorder, 1, 1, 15
product = material_battleship_data_recorder, 1, 1, 8
success_sound_nickname = ui_gain_level

;; ---------------------
;; REWARD BOXES
;; ---------------------

[Equipment Blueprint Case]
type = loot
ingredient = surprise_box_blueprint_equipment01, 1
product = blueprint_cv_power_light_opt01, 1, 1, 1
product = blueprint_cv_power_medium_opt01, 1, 1, 1
product = blueprint_cv_power_heavy_opt01, 1, 1, 1
product = blueprint_ge_cloak_capital_light_std01, 1, 1, 1
product = blueprint_ge_cloak_capital_medium_std01, 1, 1, 1
product = blueprint_ge_cloak_capital_heavy_std01, 1, 1, 1
product = blueprint_ou_engine_transport01, 1, 1, 1
product = blueprint_ou_engine_train01, 1, 1, 1
product = blueprint_corsair_engine_transport01, 1, 1, 1
product = blueprint_corsair_engine_train01, 1, 1, 1
success_sound_nickname = ui_gain_level

[Weapons Blueprint Case]
type = loot
ingredient = surprise_box_blueprint_guns01, 1
product = blueprint_special_gun01, 1, 1, 1
product = blueprint_special_gun02, 1, 1, 1
product = blueprint_special_gun03, 1, 1, 1
product = blueprint_special_gun04, 1, 1, 1
product = blueprint_special_gun05, 1, 1, 1
product = blueprint_special_gun06, 1, 1, 1
product = blueprint_special_gun07, 1, 1, 1
product = blueprint_special_gun08, 1, 1, 1
product = blueprint_special_gun09, 1, 1, 1
product = blueprint_special_gun10, 1, 1, 1
product = blueprint_special_gun11, 1, 1, 1
product = blueprint_special_gun12, 1, 1, 1
product = blueprint_special_gun13, 1, 1, 1
product = blueprint_special_gun14, 1, 1, 1
product = blueprint_special_gun15, 1, 1, 1
product = blueprint_special_gun16, 1, 1, 1
product = blueprint_special_gun17, 1, 1, 1
product = blueprint_special_gun18, 1, 1, 1
product = blueprint_special_gun19, 1, 1, 1
product = blueprint_special_gun20, 1, 1, 1
product = blueprint_special_gun21, 1, 1, 1
product = blueprint_sp_particle_light01, 1, 1, 1
product = blueprint_sp_laser_heavy01, 1, 1, 1
product = blueprint_gun_codename_plasma_special01, 1, 1, 1
product = blueprint_gun_codename_plasma_special02, 1, 1, 1
product = blueprint_gun_codename_plasma_special03, 1, 1, 1
product = blueprint_gun_codename_repair_special01, 1, 1, 1
success_sound_nickname = ui_gain_level

[FL:SR Surprise Box]
type = loot
ingredient = surprise_box_flsr01, 1
product = li_gun_laser_heavy01, 1, 1, 1
product = br_gun_tachyon_heavy01, 1, 1, 1
product = rh_gun_tachyon_heavy01, 1, 1, 1
product = ku_gun_neutron_heavy02, 1, 1, 1
product = fc_b_gun_tachyon_heavy01, 1, 1, 1
product = fc_bd_gun_laser_heavy01, 1, 1, 1
product = fc_h_gun_plasma_heavy01, 1, 1, 1
product = fc_lr_gun_laser_heavy01, 1, 1, 1
product = fc_m_gun_neutron_heavy02, 1, 1, 1
product = fc_rh_gun_laser_heavy02, 1, 1, 1
product = fc_lh_gun_pulse_medium01, 1, 1, 1
product = fc_x_gun_particle_heavy02, 1, 1, 1
product = gd_z_missile_heavy01, 1, 1, 1
product = gd_bh_gun_particle_heavy02, 1, 1, 1
product = fc_ou_gun_tachyon_heavy02, 1, 1, 1
product = fc_c_gun_neutron_heavy02, 1, 1, 1
product = gd_gm_gun_photon_heavy01, 1, 1, 1
product = fc_sds_gun_photon_heavy01, 1, 1, 1
product = fc_or_gun_laser_heavy01, 1, 1, 1
success_sound_nickname = ui_gain_level

;; ---------------------
;; SEASON EVENT BOXES
;; ---------------------

[Trick or Treat Bucket]
type = loot
ingredient = surprise_box_event_halloween01, 1
product = material_halloween_pumpkin, 1, 1, 95
product = blueprint_halloween_br_gun_tachyon_light01, 1, 1, 15
product = blueprint_halloween_br_gun_tachyon_medium01, 1, 1, 15
product = blueprint_halloween_engine_fighter_light01, 1, 1, 10
product = blueprint_halloween_engine_fighter_heavy01, 1, 1, 10
success_sound_nickname = ui_gain_level

[Christmas Present]
type = loot
ingredient = surprise_box_event_christmas01, 1
ingredient = surprise_ingredient_event_christmas01, 1
product = blueprint_christmas_santa_gun_plasma_heavy01, 1, 1, 2
product = blueprint_christmas_heavy_fighter_engine01, 1, 1, 2
product = blueprint_christmas_engine_freighter01, 1, 1, 2
product = blueprint_christmas_engine_transport01, 1, 1, 1
product = blueprint_christmas_engine_train01, 1, 1, 1
success_sound_nickname = ui_gain_level

[Naughty Present]
type = loot
ingredient = surprise_box_event_christmas02, 1
product = fc_gb_gun_laser_light02, 1, 1, 145
product = fc_gb_gun_laser_medium02, 1, 1, 145
product = fc_gb_gun_plasma_heavy02, 1, 1, 145
product = gd_ww_engine_transport01, 1, 1, 125
product = gd_ww_engine_train01, 1, 1, 125
product = gb_engine_fighter_light01, 1, 1, 145
product = gb_engine_fighter_heavy01, 1, 1, 145
product = torpedo01_mark02, 1, 1, 25
success_sound_nickname = ui_gain_level

[Spring Event Box]
type = loot
ingredient = surprise_box_event_spring01, 1
product = gd_ww_gun_laser_light02, 1, 1, 200
product = gd_ww_gun_laser_medium02, 1, 1, 200
product = gd_ww_turret_laser_light02, 1, 1, 100
product = gd_ww_turret_laser_medium02, 1, 1, 100
product = gd_ww_engine_fighter_heavy01, 1, 1, 75
product = gd_ww_engine_freighter01, 1, 1, 75
product = gd_ww_engine_transport01, 1, 1, 75
product = gd_ww_engine_train01, 1, 1, 75
product = named_box_hakkera, 1, 1, 10
product = blueprint_spring_light_fighter_engine01, 1, 1, 30
product = blueprint_spring_heavy_fighter_engine01, 1, 1, 30
product = blueprint_spring_engine_freighter01, 1, 1, 30
success_sound_nickname = ui_gain_level

[Summer Event Box]
type = loot
ingredient = surprise_box_event_summer01, 1
product = fc_gb_gun_laser_light01, 1, 1, 200
product = fc_gb_gun_laser_medium01, 1, 1, 200
product = fc_gb_gun_laser_light02, 1, 1, 100
product = fc_gb_gun_laser_medium02, 1, 1, 100
product = gb_engine_fighter_light01, 1, 1, 75
product = gb_engine_fighter_heavy01, 1, 1, 75
product = fc_gb_gun_plasma_heavy02, 1, 1, 50
product = gb_engine_transport01, 1, 1, 50
product = gb_engine_train01, 1, 1, 50
product = named_box_von_claussen, 1, 1, 10
product = blueprint_summer_light_fighter_engine01, 1, 1, 30
product = blueprint_summer_heavy_fighter_engine01, 1, 1, 30
product = blueprint_summer_engine_freighter01, 1, 1, 30
success_sound_nickname = ui_gain_level

[Autumn Event Box]
type = loot
ingredient = surprise_box_event_autumn01, 1
product = fc_gb_gun_laser_light01, 1, 1, 200
product = fc_gb_gun_laser_medium01, 1, 1, 200
product = fc_gb_gun_laser_light02, 1, 1, 100
product = fc_gb_gun_laser_medium02, 1, 1, 100
product = gb_engine_fighter_light01, 1, 1, 75
product = gb_engine_fighter_heavy01, 1, 1, 75
product = fc_gb_gun_plasma_heavy02, 1, 1, 50
product = gb_engine_transport01, 1, 1, 50
product = gb_engine_train01, 1, 1, 50
product = named_box_tobias, 1, 1, 10
product = blueprint_autumn_light_fighter_engine01, 1, 1, 30
product = blueprint_autumn_heavy_fighter_engine01, 1, 1, 30
product = blueprint_autumn_engine_freighter01, 1, 1, 30
success_sound_nickname = ui_gain_level

[Winter Event Box]
type = loot
ingredient = surprise_box_event_winter01, 1
product = gd_ww_gun_laser_light02, 1, 1, 200
product = gd_ww_gun_laser_medium02, 1, 1, 200
product = gd_ww_turret_laser_light02, 1, 1, 100
product = gd_ww_turret_laser_medium02, 1, 1, 100
product = gd_ww_engine_fighter_heavy01, 1, 1, 75
product = gd_ww_engine_freighter01, 1, 1, 75
product = gd_ww_engine_transport01, 1, 1, 75
product = gd_ww_engine_train01, 1, 1, 75
product = named_box_king, 1, 1, 10
product = blueprint_winter_light_fighter_engine01, 1, 1, 30
product = blueprint_winter_heavy_fighter_engine01, 1, 1, 30
product = blueprint_winter_engine_freighter01, 1, 1, 30
success_sound_nickname = ui_gain_level

;; ---------------------
;; NAMED BOXES
;; ---------------------

[HOVIS PAYBACK BOX]
type = loot
ingredient = named_box_hovis, 1
product = hovis_gun_photon_light01, 1, 1, 30
product = hovis_gun_photon_medium01, 1, 1, 30
product = hovis_engine_fighter_light01, 1, 1, 15
product = hovis_engine_fighter_heavy01, 1, 1, 15
product = hovis_engine_freighter01, 1, 1, 10
success_sound_nickname = ui_gain_level

[HAKKERAS HONOR BOX]
type = loot
ingredient = named_box_hakkera, 1
product = hakkera_gun_neutron_medium01, 1, 1, 30
product = hakkera_gun_neutron_heavy01, 1, 1, 30
product = hakkera_engine_fighter_light01, 1, 1, 15
product = hakkera_engine_fighter_heavy01, 1, 1, 15
product = hakkera_engine_freighter01, 1, 1, 10
success_sound_nickname = ui_gain_level

[KINGS STAR & STRIPES BOX]
type = loot
ingredient = named_box_king, 1
product = king_gun_laser_light01, 1, 1, 30
product = king_gun_laser_medium01, 1, 1, 30
product = king_engine_fighter_light01, 1, 1, 15
product = king_engine_fighter_heavy01, 1, 1, 15
product = king_engine_freighter01, 1, 1, 10
success_sound_nickname = ui_gain_level

[JUNIS DUTY BOX]
type = loot
ingredient = named_box_juni, 1
product = juni_gun_tachyon_light01, 1, 1, 30
product = juni_gun_laser_heavy01, 1, 1, 30
product = juni_engine_fighter_light01, 1, 1, 15
product = juni_engine_fighter_heavy01, 1, 1, 15
product = juni_engine_freighter01, 1, 1, 10
success_sound_nickname = ui_gain_level

[TOBIASS CHARM BOX]
type = loot
ingredient = named_box_tobias, 1
product = tobias_gun_particle_medium01, 1, 1, 30
product = tobias_gun_particle_heavy01, 1, 1, 30
product = tobias_engine_fighter_light01, 1, 1, 15
product = tobias_engine_fighter_heavy01, 1, 1, 15
product = tobias_engine_freighter01, 1, 1, 10
success_sound_nickname = ui_gain_level

[VON CLAUSSENS COURAGE BOX]
type = loot
ingredient = named_box_von_claussen, 1
product = von_claussen_gun_tachyon_light01, 1, 1, 30
product = von_claussen_gun_tachyon_medium01, 1, 1, 30
product = von_claussen_engine_fighter_light01, 1, 1, 15
product = von_claussen_engine_fighter_heavy01, 1, 1, 15
product = von_claussen_engine_freighter01, 1, 1, 10
success_sound_nickname = ui_gain_level
