;; In-game command:
; /craft <Recipe Name> <amount>
; /dismantle <Recipe Name> <amount>
; /loot <Recipe Name> <amount>

;; Syntax:
; [<Recipe Name>]
; type = produce/dismantle/loot
; product = <good nickname>, <min amount>, <max amount>, <weighted chance> ;multiple times allowed
; ingredient = <good nickname>, <amount> ;multiple times allowed
; cost = <amount> ;optional
; base_nickname = <base nickname> ;optional, multiple times allowed
; ship_nickname = <shiparch nickname> ;optional, multiple times allowed
; success_sound_nickname = <sound nickname> ;optional

;;; ----------------------------
;; SHIP CRAFTING
;; ----------------------------

;; - Medium Transport -
;; 		Available on:
;;				All Shipyards

[Transport]
type = produce
product = package_ge_medium_transport
ingredient = blueprint_medium_transport01, 1
ingredient = material_mod_package_std01, 25
cost = 50000000
ship_nickname = ge_transport_player
base_nickname = Rh01_02_base
base_nickname = Rh02_04_base
base_nickname = Rh04_07_base
base_nickname = Li01_14_base
base_nickname = Li01_07_base
base_nickname = Li05_04_base
base_nickname = Br01_02_base
base_nickname = Br06_06_base
base_nickname = Rh04_08_base
base_nickname = Ku01_03_base
base_nickname = Ku04_03_base
base_nickname = Ku07_02_base
success_sound_nickname = Crafting_successful_light

;; - Large Transport -
;; 		Available on:
;;				All Shipyards

[Large Transport]
type = produce
product = package_ge_large_transport
ingredient = blueprint_large_transport01, 1
ingredient = material_mod_package_std01, 50
cost = 50000000
ship_nickname = ge_medium_transport_player
base_nickname = Rh01_02_base
base_nickname = Rh02_04_base
base_nickname = Rh04_07_base
base_nickname = Li01_14_base
base_nickname = Li01_07_base
base_nickname = Li05_04_base
base_nickname = Br01_02_base
base_nickname = Br06_06_base
base_nickname = Rh04_08_base
base_nickname = Ku01_03_base
base_nickname = Ku04_03_base
base_nickname = Ku07_02_base
success_sound_nickname = Crafting_successful_light

;; - Medium Train -
;; 		Available on:
;;				All Shipyards

[Train]
type = produce
product = package_ge_large_train
ingredient = blueprint_medium_train01, 1
ingredient = material_mod_package_std01, 75
cost = 50000000
ship_nickname = ge_train_player
base_nickname = Rh01_02_base
base_nickname = Rh02_04_base
base_nickname = Rh04_07_base
base_nickname = Li01_14_base
base_nickname = Li01_07_base
base_nickname = Li05_04_base
base_nickname = Br01_02_base
base_nickname = Br06_06_base
base_nickname = Rh04_08_base
base_nickname = Ku01_03_base
base_nickname = Ku04_03_base
base_nickname = Ku07_02_base
success_sound_nickname = Crafting_successful_light

;; - Large Train -
;; 		Available on:
;;				All Shipyards

[Large Train]
type = produce
product = package_ge_very_large_train
ingredient = blueprint_large_train01, 1
ingredient = material_mod_package_std01, 100
cost = 50000000
ship_nickname = ge_large_train_player
base_nickname = Rh01_02_base
base_nickname = Rh02_04_base
base_nickname = Rh04_07_base
base_nickname = Li01_14_base
base_nickname = Li01_07_base
base_nickname = Li05_04_base
base_nickname = Br01_02_base
base_nickname = Br06_06_base
base_nickname = Rh04_08_base
base_nickname = Ku01_03_base
base_nickname = Ku04_03_base
base_nickname = Ku07_02_base
success_sound_nickname = Crafting_successful_light

;; - Sabre Strike -
;; 		Available on:
;;				All Shipyards

[Sabre Strike]
type = produce
product = package_bw_elite2_variant01
ingredient = blueprint_bw_elite2_variant01, 1
ingredient = material_mod_package_std01, 1
cost = 1000000
ship_nickname = bw_elite2
success_sound_nickname = Crafting_successful_light

;; - Hamerhead Interceptor-
;; 		Available on:
;;				All Shipyards

[Hammerhead Interceptor]
type = produce
product = package_bh_elite2_variant01
ingredient = blueprint_bh_elite2_variant01, 1
ingredient = material_mod_package_adv01, 1
cost = 1000000
ship_nickname = bh_elite2
success_sound_nickname = Crafting_successful_light






