;; In-game command:
; /craft <Recipe Name> <amount>
; /dismantle <Recipe Name> <amount>
; /loot <Recipe Name> <amount>

;; Syntax:
; [<Recipe Name>]
; type = produce/dismantle/loot
; product = <good nickname>, <min amount>, <max amount>, <weighted chance> ;multiple times allowed
; ingredient = <good nickname>, <amount> ;multiple times allowed
; cost = <amount> ;optional
; base_nickname = <base nickname> ;optional, multiple times allowed
; ship_nickname = <shiparch nickname> ;optional, multiple times allowed
; success_sound_nickname = <sound nickname> ;optional

;; ----------------------------
;; KEY CRAFTS
;; ----------------------------

;; - SANTA VON CLAUSSEN´S CHRISTMAS PRESENT KEY -
;; 		Available on:
;;				Everywhere

[Christmas Key]
type = produce
product = surprise_key_event_christmas01, 1
ingredient = material_christmas_snowball, 200
success_sound_nickname = Crafting_successful_electrical

;; ----------------------------
;; SURPRISE BOX CRAFTS
;; ----------------------------

;; - NAUGHTY PRESENT BOX -
;; 		Available on:
;;				Everywhere

[Naughty Present]
type = produce
product = surprise_box_event_christmas02, 1
ingredient = material_christmas_snowball, 200
ingredient = commodity_hydrocarbons, 20
success_sound_nickname = Crafting_successful_consumer
