#pragma once

namespace Missions
{
	enum class ActionType
	{
		Act_ActTrig,
		Act_AddCargo,
		Act_AddLabel,
		Act_AdjAcct,
		Act_AdjHealth,
		Act_Cloak,
		Act_DeactTrig,
		Act_DebugMsg,
		Act_Destroy,
		Act_DisableTradelane,
		Act_DockRequest,
		Act_EndMission,
		Act_EtherComm,
		Act_ForceLand,
		Act_GiveObjList,
		Act_Invulnerable,
		Act_LightFuse,
		Act_LockDock,
		Act_MarkObj,
		Act_PlayMusic,
		Act_PlayNN,
		Act_PlaySoundEffect,
		Act_PopUpDialog,
		Act_RandomPopSphere,
		Act_RemoveCargo,
		Act_RemoveLabel,
		Act_SendComm,
		Act_SetNNObj,
		Act_SetRep,
		Act_SetVibe,
		Act_SpawnFormation,
		Act_SpawnLoot,
		Act_SpawnShip,
		Act_SpawnShipRel,
		Act_SpawnSolar,
		Act_Uncloak,
		Act_UnlockDock,
		Act_UnmarkObj,
	};
}