[Mission]
nickname = openworld_bw04_abgrundFX
initstate = ACTIVE

;;Cnd_InZone is not particularly helpful in this case since the "OUTSIDE" zone condition does not yet exist
[Trigger]
nickname = enter_abgrund
initstate = ACTIVE
repeatable = AUTO
Cnd_DistVec = STRANGER, 0, 0, 0, 21000, Bw04, INSIDE
Act_LightFuse = ACTIVATOR, gf_fuming_all_weakpoints
Act_AddLabel = ACTIVATOR, player_burning
Act_DebugMsg = enter_abgrund triggered
Act_PlaySoundEffect = ACTIVATOR, object_on_fire01


[Trigger]
nickname = leave_abgrund
initstate = ACTIVE
repeatable = AUTO
Cnd_DistVec = player_burning, 0, 0, 0, 21000, Bw04, OUTSIDE
;Act_LightFuse = ACTIVATOR, gf_fuming_all_weakpoints, 0, 0.1
Act_RemoveLabel = ACTIVATOR, player_burning
Act_DebugMsg = leave_abgrund triggered
Act_PlaySoundEffect = ACTIVATOR, object_on_fire02
;Act_LeaveMsn = ACTIVATOR

[Trigger]
nickname = leave_abgrund_teleportaway
initstate = ACTIVE
repeatable = AUTO
Cnd_SystemSpaceExit = player_burning, Any
;Act_LightFuse = ACTIVATOR, gf_fuming_all_weakpoints, 0, 0.1
Act_RemoveLabel = ACTIVATOR, player_burning
Act_DebugMsg = leave_abgrund_teleportaway triggered
Act_PlaySoundEffect = ACTIVATOR, object_on_fire02
;Act_LeaveMsn = ACTIVATOR