name: Publish Dev version

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    permissions:
        contents: read
        pages: write
        id-token: write
    steps:
        - name: Check out source repository
          uses: actions/checkout@v2

        - uses: darklab8/infra/.github/actions/checkout-freelancer@master
          with:
            freelancer-mod: "vanilla"
            freelancer-folder: ${{ github.workspace }}/freelancer_folder
            ssh-key-base64-vanilla: ${{ secrets.ID_RSA_FILES_FREELANCER_VANILLA }}

        - name: Set up Go
          uses: darklab8/infra/.github/actions/install-go@master
        
        - name: Install flsr patcher
          run: go install github.com/darklab8/fl-data-flsr@latest
        - name: Merge latest FLSR files (from Freelancer folder) to clean vanilla (to freelancer_folder)
          run: fl-data-flsr -wd ${{ github.workspace }}/freelancer_folder
        - name: Sprinkle with FLSR recipes
          run: |
            mkdir -p ${{ github.workspace }}/freelancer_folder/EXE/flhook_plugins/crafting
            cp Freelancer/EXE/flhook_plugins/crafting/* ${{ github.workspace }}/freelancer_folder/EXE/flhook_plugins/crafting/

        - uses: darklab8/fl-darkstat/.github/actions/build@master
          with:
            site-root: "/FLSR/"
            freelancer-folder: ${{ github.workspace }}/freelancer_folder
            heading: <a href="https://github.com/darklab8/fl-darkstat">Darkstat</a> from <a href="https://darklab8.github.io/blog/pet_projects.html#Freelancercommunity">DarkTools</a> for <a href="https://github.com/darklab8/fl-data-flsr">FLSR</a> of <a href="https://github.com/Freelancer-Sirius-Revival/FLSR/commit/${{ github.sha }}">PREVIEW ${{ github.sha }}</a>
            command: --stat-deals-on build
            map-on: "true"
            map-index-url: map.html
            disable-dev-mode: "false"

        - uses: actions/upload-pages-artifact@v3
          with:
            name: github-pages
            path: ./build
        
        # Turn on ability to deploy to pages in repository settings, Pages tab
        # choose "Github Actions" deployment method to Pages
        - name: Deploy to pages
          uses: actions/deploy-pages@v4
          id: deployment
          continue-on-error: true
